### ISSUE TITLE
Preview of image does not scale the image when it is too large

### ISSUE THREAD

**Issue by Markionium** [dhis2/settings-app#14] opened 2015-11-06 00:50 UTC
![image](https://cloud.githubusercontent.com/assets/2134901/10986258/ccd39b1c-8428-11e5-9a5a-a57dbe839f74.png)

**Comment by alexklibisz** [comment] 2016-03-11 20:54
I'm a potential GSOC applicant.

I wanted to get a look into the code so I took a swing at this issue here: https://github.com/dhis2/settings-app/pull/45

I'm happy to revise if needed.

Thanks!

**Comment by alexklibisz** [comment] 2016-03-11 21:06
Also, two related things I noticed:

1. If you set a large image as the logo image, then it adjusts correctly in the settings web app, but it shows the full image on the login screen and on the home dashboard (I'm running the DHIS-Live JAR):

![image](https://cloud.githubusercontent.com/assets/8015228/13715361/329a9f90-e7a2-11e5-90f4-b5d0f8f1f5db.png)

![image](https://cloud.githubusercontent.com/assets/8015228/13715320/02399860-e7a2-11e5-860a-9241e7be82b0.png)

2. I noticed that the Dialog component gets positioned disproportionately far down the screen initially, and then when you adjust the window width it gets centered. I looked into the material-ui source for how they implement the Dialog Component, and it looks like it has to do with how top-padding is calculated. I tried to set something like `<Dialog ... style={{paddingTop: '10px'}} ... >`, but the padding gets recalculated with JS in the Dialog component itself. I noticed the behavior in Chrome and Firefox on Fedora. Here's a GIF:

![image](https://cloud.githubusercontent.com/assets/8015228/13715483/0364240c-e7a3-11e5-8acf-174f9780445e.png)

**Comment by nicolayr** [comment] 2016-03-14 13:06
Thanks for the pull request @alexklibisz - I'm merging now.

Regarding the issue you mention with incorrect scaling of the header bar image on different pages, that's caused by the fact that there are two versions of the header bar: One is a D2-UI component, and the other is a more general version. The D2-UI version scales the image correctly and is used in all the new front end apps, while the older version does not scale the image, and is used basically everywhere else. So this will be fixed gradually over time as we rewrite more of the apps.

As for the 2nd issue, as you say this seems to be an issue with Material-UI. If you have the time and inclination, you could report it directly to Material-UI. You could even fix it and send them a pull request :)

**Closed** 2016-03-14 13:12 UTC
Labels: enhancement, help wanted
