### ISSUE TITLE
IE10 seems to cache approval levels api request

### ISSUE THREAD

**Issue by Markionium** [dhis2/settings-app#13] opened 2015-11-06 00:49 UTC
Reproduce:
+ Add approval level in IE10
+ List of approval levels stays the same, but is actually updated
+ Clean cache or check in chrome to see updated version

**Comment by Markionium** [comment] 2015-11-06 11:07
This might not only be related to approval levels. It might also cache other requests (OAuth2, or other lists)

**Comment by nicolayr** [comment] 2016-09-28 16:01
Can't reproduce - closing for now.

**Closed by nicolayr** 2016-09-28 16:01 UTC
Labels: bug, help wanted, priority:low
